# Generated by Django 5.0.3 on 2024-04-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Background', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='locations',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
